### PR TITLE
join community groups api endpoint

### PR DESCRIPTION
**Pull request by jnogle**

### CODE REVIEW

**Comment by jnogle** [comment]
I was having trouble with the asynchronous nature of javascript when after the forEach loop that goes through all the leaders and adds them to the leader info array, that array would be empty when I'd try to send it back. The way I got around it was by sending the notifications inside that loop one by one instead of all at once after the loop is over. The only thing we lose is the ability to send back the leader info the the http response. If you want to mess with that further you can but I wasn't able to figure anything out, but if you think that's fine you can go ahead and merge it.

**Comment by jnogle** [comment]
For testing the token authentication, I used a python firebase id token generator I found here https://github.com/jewang/firebase-id-token-generator-python

**Comment by fedorareis** [comment]
I want to play around with this one a bit before I approve it, but I haven't had any time lately. Hopefully, I can look at it this weekend.

**Review by fedorareis — APPROVED** [review]
I want to look more into the issue that was being had with the loop, but this needs to go live in the meantime. It can be addressed at some point in the future since it won't result in a major change.

**Pull request merged**
